---
- name: Provisioning some AWS stuff
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - secret.yml

  tasks:
    - name: Find the current windows AMI in region
      ec2_ami_info:
        region: "{{ ec2_region }}"
        filters:
#          name: Windows_Server-2019-English-Core-Base*
          name: Windows_Server-2012-R2_RTM-English-64Bit-Base-*
      register: found_amis

    - set_fact:
        win_ami_id: "{{ (found_amis.images | last ).image_id }}"

    - name: Provision a set of instances
      ec2: 
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ win_ami_id }}"
        region: "{{ ec2_region }}"
        instance_tags: "{'ansible_group':'windows_webservers_phillyair', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_phillyair'}"
        exact_count: "{{ ec2_instance_count }}"
        count_tag: 
           Name: demo_phillyair
        wait: true
        user_data: "{{ lookup('template', 'userdata.txt.j2') }}"
      register: ec2

      tags:
        - web

    - name: Wait for the WinRM to answer on all of the hosts
      wait_for:
        port: 5986
        host: "{{ item.public_ip }}"
        timeout: 300
      with_items: '{{ec2.tagged_instances}}'

