---
- name: Provisioning some AWS stuff
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - secret.yml

  tasks:

    - name: Provision a set of instances
      ec2: 
        group: "{{ ec2_security_group }}"
        type: "{{ ec2_instance_type }}"
        image: "{{ ec2_ami_id }}"
        region: "{{ ec2_region }}"
        instance_tags: "{'ansible_group':'windows_webservers_phillyair', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_phillyair'}"
        exact_count: "{{ ec2_instance_count }}"
        count_tag: 
           Name: demo_phillyair
        wait: true
        user_data: "{{ lookup('template', 'userdata.txt.j2') }}"
      register: ec2

      tags:
        - web

    - debug: var=ec2

    - name: Wait for the WinRM to answer on all of the hosts
      wait_for:
        port: 5986
        host: "{{ item.public_ip }}"
        timeout: 300
      with_items: '{{ec2.tagged_instances}}'

