---
- name: Do something with those instances
  hosts: all
  connection: winrm
#  gather_facts: False
  vars:
    nginx_version: "1.12.2"
 
  vars_files:
    - secret.yml

  tasks:
    - name: install nginx
      win_chocolatey:
        name: nginx
        state: present
        version: "{{ nginx_version }}"

    - name: install nssm
      win_chocolatey:
        name: nssm
        state: present

    - name: install nginx as service
      win_nssm:
        name: nginx
        application: 'C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}\nginx.exe'
        app_parameters_free_form: '-c C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}\conf\nginx.conf -p C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}'
        stdout_file: C:\nginx_out.txt
        stderr_file: C:\nginx_error.txt
      notify:
        - start nginx

    - name: Firewall rule to allow HTTP on TCP port 80
      win_firewall_rule:
        name: HTTP
        localport: 80
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes


  handlers:
    - name: start nginx
      win_service:
        name: nginx
        state: started
