---
# This role contains common plays that will run on all nodes.
- name: Update the Centos repo to vault
  copy:
    src: CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    force: yes

- name: Install python bindings for SE Linux
  yum:
    name:
      - libselinux-python
      - libsemanage-python
    state: present

- name: Update the curl and nss packages to latest
  yum:
    name:
      - curl
      - nss
    state: latest

- name: Create the repository for EPEL
  copy:
    src: epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy:
    src: RPM-GPG-KEY-EPEL-6
    dest: /etc/pki/rpm-gpg

- name: install some useful nagios plugins
  yum:
    name: 
      - nagios-nrpe
      - nagios-plugins-swap
      - nagios-plugins-users
      - nagios-plugins-procs
      - nagios-plugins-load
      - nagios-plugins-disk
    state: present

- name: Configure nrpe file
  template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
  notify: restart nrpe

- name: Install ntp
  yum:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

# work around RHEL 7, for now
- name: insert iptables template
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
  when: ansible_distribution_major_version != '7'
  notify: restart iptables

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
